<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Test Report</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    
<style type="text/css" media="screen">
body        { font-family: verdana, arial, helvetica, sans-serif; font-size: 80%; }
table       { font-size: 100%; }
pre         { }

/* -- heading ---------------------------------------------------------------------- */
h1 {
	font-size: 16pt;
	color: gray;
}
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}

.heading .attribute {
    margin-top: 1ex;
    margin-bottom: 0;
}

.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}

/* -- css div popup ------------------------------------------------------------------------ */
a.popup_link {
}

a.popup_link:hover {
    color: red;
}

.popup_window {
    display: none;
    position: relative;
    left: 0px;
    top: 0px;
    /*border: solid #627173 1px; */
    padding: 10px;
    background-color: #E6E6D6;
    font-family: "Lucida Console", "Courier New", Courier, monospace;
    text-align: left;
    font-size: 8pt;
    width: 500px;
}

}
/* -- report ------------------------------------------------------------------------ */
#show_detail_line {
    margin-top: 3ex;
    margin-bottom: 1ex;
}
#result_table {
    width: 80%;
    border-collapse: collapse;
    border: 1px solid #777;
}
#header_row {
    font-weight: bold;
    color: white;
    background-color: #777;
}
#result_table td {
    border: 1px solid #777;
    padding: 2px;
}
#total_row  { font-weight: bold; }
.passClass  { background-color: #6c6; }
.failClass  { background-color: #c60; }
.errorClass { background-color: #c00; }
.passCase   { color: #6c6; }
.failCase   { color: #c60; font-weight: bold; }
.errorCase  { color: #c00; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }


/* -- ending ---------------------------------------------------------------------- */
#ending {
}

</style>

</head>
<body>
<script language="javascript" type="text/javascript"><!--
output_list = Array();

/* level - 0:Summary; 1:Failed; 2:All */
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level < 1) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level > 1) {
                tr.className = '';
            }
            else {
                tr.className = 'hiddenRow';
            }
        }
    }
}


function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        tid0 = 't' + cid.substr(1) + '.' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        if (toHide) {
            document.getElementById('div_'+tid).style.display = 'none'
            document.getElementById(tid).className = 'hiddenRow';
        }
        else {
            document.getElementById(tid).className = '';
        }
    }
}


function showTestDetail(div_id){
    var details_div = document.getElementById(div_id)
    var displayState = details_div.style.display
    // alert(displayState)
    if (displayState != 'block' ) {
        displayState = 'block'
        details_div.style.display = 'block'
    }
    else {
        details_div.style.display = 'none'
    }
}


function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}

/* obsoleted by detail in <div>
function showOutput(id, name) {
    var w = window.open("", //url
                    name,
                    "resizable,scrollbars,status,width=800,height=450");
    d = w.document;
    d.write("<pre>");
    d.write(html_escape(output_list[id]));
    d.write("\n");
    d.write("<a href='javascript:window.close()'>close</a>\n");
    d.write("</pre>\n");
    d.close();
}
*/
--></script>

<div class='heading'>
<h1>Test Report</h1>
<p class='attribute'><strong>Start Time:</strong> 2017-11-21 09:49:31</p>
<p class='attribute'><strong>Duration:</strong> 0:00:00.156000</p>
<p class='attribute'><strong>Status:</strong> Error 11</p>

<p class='description'>Test Description</p>
</div>



<p id='show_detail_line'>Show
<a href='javascript:showCase(0)'>Summary</a>
<a href='javascript:showCase(1)'>Failed</a>
<a href='javascript:showCase(2)'>All</a>
</p>
<table id='result_table'>
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row'>
    <td>Test Group/Test case</td>
    <td>Count</td>
    <td>Pass</td>
    <td>Fail</td>
    <td>Error</td>
    <td>View</td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaLogin_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c1',1)">Detail</a></td>
</tr>

<tr id='ft1.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_guanjia_login</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.1')" >
        error</a>

    <div id='div_ft1.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.1: 将json格式params去掉空格、换行:  {"mobile":"18211078892","source":1,"password":"12345678","version":"1.1.0"}
加密后的密文： lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W+dF3foXbKM/lLZnKHEnTgnfaFo+95g5DNLRpxJeSBbhHXZpvIVM5Em2mOV+KfZMwnvEA=
接口地址： http://dev.efang100.cc/steward/common/login
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case01_guanjia_login.py", line 88, in test_guanjia_login
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='dev.efang100.cc', port=80): Max retries exceeded with url: /steward/common/login?encrypt=DES&amp;param=lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W%2BdF3foXbKM%2FlLZnKHEnTgnfaFo%2B95g5DNLRpxJeSBbhHXZpvIVM5Em2mOV%2BKfZMwnvEA%3D&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000000027C51D0&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaLogin_1</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c2',1)">Detail</a></td>
</tr>

<tr id='ft2.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_guanjia_login</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft2.1')" >
        error</a>

    <div id='div_ft2.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft2.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft2.1: 将json格式params去掉空格、换行:  {"mobile":"182110788922","source":1,"password":"12345678","version":"1.1.0"}
加密后的密文： lAHyQ4545oY2eyfKi2uvPegffhrL9oFmkuHAEegJZ0JtqGZr6qdlwdh4DTr6wXJYndFuu/5NXVt2LFwDThYvBRlT5YqdIL0FLzQIGsgR3rQ=
接口地址： http://dev.efang100.cc/steward/common/login
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case01_guanjia_login.py", line 88, in test_guanjia_login
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='dev.efang100.cc', port=80): Max retries exceeded with url: /steward/common/login?encrypt=DES&amp;param=lAHyQ4545oY2eyfKi2uvPegffhrL9oFmkuHAEegJZ0JtqGZr6qdlwdh4DTr6wXJYndFuu%2F5NXVt2LFwDThYvBRlT5YqdIL0FLzQIGsgR3rQ%3D&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002808FD0&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaLogin_2</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c3',1)">Detail</a></td>
</tr>

<tr id='ft3.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_guanjia_login</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.1')" >
        error</a>

    <div id='div_ft3.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.1: 将json格式params去掉空格、换行:  {"mobile":"18211078892","source":1,"password":"1234567890","version":"1.1.0"}
加密后的密文： lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W+dF3foXbKM/lLZnKHEnTgnfaFZswITdfF4qToUnDn3Xxx7EGWv3u8XQry/4I93FDif4I=
接口地址： http://dev.efang100.cc/steward/common/login
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case01_guanjia_login.py", line 88, in test_guanjia_login
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='dev.efang100.cc', port=80): Max retries exceeded with url: /steward/common/login?encrypt=DES&amp;param=lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W%2BdF3foXbKM%2FlLZnKHEnTgnfaFZswITdfF4qToUnDn3Xxx7EGWv3u8XQry%2F4I93FDif4I%3D&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000000028089B0&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaModifyPwd_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c4',1)">Detail</a></td>
</tr>

<tr id='ft4.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_modify_pwd</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.1')" >
        error</a>

    <div id='div_ft4.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.1: 将json格式params去掉空格、换行:  {"mobile":"18211078892","source":1,"version":"1.1.0","type_id":"3"}
加密后的密文： lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W+dF2UUit9h+dlA8CEFaqt9XaYoYzh3DkmOffvOys5CMzcJunORAjGPQxo
接口地址： http://dev.efang100.cc/steward/common/getSmsCode
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case03_guanjia_modifypwd.py", line 91, in test_modify_pwd
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='dev.efang100.cc', port=80): Max retries exceeded with url: /steward/common/getSmsCode?encrypt=DES&amp;param=lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W%2BdF2UUit9h%2BdlA8CEFaqt9XaYoYzh3DkmOffvOys5CMzcJunORAjGPQxo&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002808630&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaModifyPwd_1</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c5',1)">Detail</a></td>
</tr>

<tr id='ft5.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_modify_pwd</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.1')" >
        error</a>

    <div id='div_ft5.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft5.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft5.1: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\paramunittest.py", line 89, in setUp
    self.setParameters(*parameters[0], **parameters[1])
  File "D:\interfaceTest\testCase\case_guanjia_old\case03_guanjia_modifypwd.py", line 48, in setParameters
    yzm = configDB.MyDB().zhiyu_yzm(sql)
  File "D:\interfaceTest\common\configDB.py", line 87, in zhiyu_yzm
    cursor = self.executeSQL(sql)
  File "D:\interfaceTest\common\configDB.py", line 53, in executeSQL
    self.cursor.execute(sql)
AttributeError: 'NoneType' object has no attribute 'execute'


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaModifyPwd_2</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c6',1)">Detail</a></td>
</tr>

<tr id='ft6.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_modify_pwd</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.1')" >
        error</a>

    <div id='div_ft6.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft6.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft6.1: 将json格式params去掉空格、换行:  {"mobile":"18211078892","source":1,"version":"1.1.0","type_id":"2"}
加密后的密文： lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W+dF2UUit9h+dlA8CEFaqt9XaYoYzh3DkmOffvOys5CMzcJkuQD6dNwZbk
接口地址： http://dev.efang100.cc/steward/common/getSmsCode
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case03_guanjia_modifypwd.py", line 91, in test_modify_pwd
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='dev.efang100.cc', port=80): Max retries exceeded with url: /steward/common/getSmsCode?encrypt=DES&amp;param=lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W%2BdF2UUit9h%2BdlA8CEFaqt9XaYoYzh3DkmOffvOys5CMzcJkuQD6dNwZbk&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002948080&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaModifyPwd_3</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c7',1)">Detail</a></td>
</tr>

<tr id='ft7.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_modify_pwd</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.1')" >
        error</a>

    <div id='div_ft7.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft7.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft7.1: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\paramunittest.py", line 89, in setUp
    self.setParameters(*parameters[0], **parameters[1])
  File "D:\interfaceTest\testCase\case_guanjia_old\case03_guanjia_modifypwd.py", line 48, in setParameters
    yzm = configDB.MyDB().zhiyu_yzm(sql)
  File "D:\interfaceTest\common\configDB.py", line 87, in zhiyu_yzm
    cursor = self.executeSQL(sql)
  File "D:\interfaceTest\common\configDB.py", line 53, in executeSQL
    self.cursor.execute(sql)
AttributeError: 'NoneType' object has no attribute 'execute'


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaAccountInfo_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c8',1)">Detail</a></td>
</tr>

<tr id='ft8.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_account_info</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.1')" >
        error</a>

    <div id='div_ft8.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.1: 1
&lt;type 'int'&gt;
token: KNu4DkcHKzRVbGJFPgFyXA4NWsVg4EoL
将json格式params去掉空格、换行:  {"access_token":"KNu4DkcHKzRVbGJFPgFyXA4NWsVg4EoL","source":1,"version":"1.1.0"}
加密后的密文： PwFy53E8NrjLcKW6L7rTtiYNpWinWqB/N7xXqV9VqC+K7MAckI+T2xIbocEZ/5BmL+5ciUUZdUjbfj/ByAKehWH4RX6NSZp/aPv9XlzopmGgbSkYpsqNYA==
接口地址： http://dev.efang100.cc/steward/account/info
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case04_guanjia_account_info.py", line 94, in test_account_info
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='dev.efang100.cc', port=80): Max retries exceeded with url: /steward/account/info?encrypt=DES&amp;param=PwFy53E8NrjLcKW6L7rTtiYNpWinWqB%2FN7xXqV9VqC%2BK7MAckI%2BT2xIbocEZ%2F5BmL%2B5ciUUZdUjbfj%2FByAKehWH4RX6NSZp%2FaPv9XlzopmGgbSkYpsqNYA%3D%3D&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000000029480B8&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaUserAvatar_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c9',1)">Detail</a></td>
</tr>

<tr id='ft9.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_user_avatar</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.1')" >
        error</a>

    <div id='div_ft9.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft9.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft9.1: 将json格式params去掉空格、换行:  {"access_token":"KNu4DkcHKzRVbGJFPgFyXA4NWsVg4EoL","source":1,"version":"1.1.0"}
加密后的密文： PwFy53E8NrjLcKW6L7rTtiYNpWinWqB/N7xXqV9VqC+K7MAckI+T2xIbocEZ/5BmL+5ciUUZdUjbfj/ByAKehWH4RX6NSZp/aPv9XlzopmGgbSkYpsqNYA==
接口地址： http://dev.efang100.cc/steward/account/avatar
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case05_guanjia_user_avatar.py", line 94, in test_user_avatar
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='dev.efang100.cc', port=80): Max retries exceeded with url: /steward/account/avatar?encrypt=DES&amp;param=PwFy53E8NrjLcKW6L7rTtiYNpWinWqB%2FN7xXqV9VqC%2BK7MAckI%2BT2xIbocEZ%2F5BmL%2B5ciUUZdUjbfj%2FByAKehWH4RX6NSZp%2FaPv9XlzopmGgbSkYpsqNYA%3D%3D&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002948630&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaSignature_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c10',1)">Detail</a></td>
</tr>

<tr id='ft10.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_signature</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft10.1')" >
        error</a>

    <div id='div_ft10.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft10.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft10.1: 将json格式params去掉空格、换行:  {"access_token":"KNu4DkcHKzRVbGJFPgFyXA4NWsVg4EoL","source":1,"version":"1.1.0"}
加密后的密文： PwFy53E8NrjLcKW6L7rTtiYNpWinWqB/N7xXqV9VqC+K7MAckI+T2xIbocEZ/5BmL+5ciUUZdUjbfj/ByAKehWH4RX6NSZp/aPv9XlzopmGgbSkYpsqNYA==
接口地址： http://dev.efang100.cc/steward/account/signature
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case06_guanjia_signature.py", line 92, in test_signature
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='dev.efang100.cc', port=80): Max retries exceeded with url: /steward/account/signature?encrypt=DES&amp;param=PwFy53E8NrjLcKW6L7rTtiYNpWinWqB%2FN7xXqV9VqC%2BK7MAckI%2BT2xIbocEZ%2F5BmL%2B5ciUUZdUjbfj%2FByAKehWH4RX6NSZp%2FaPv9XlzopmGgbSkYpsqNYA%3D%3D&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002948B00&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaVersionUpdate_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c11',1)">Detail</a></td>
</tr>

<tr id='ft11.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_version_update</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.1')" >
        error</a>

    <div id='div_ft11.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft11.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft11.1: 接口地址： http://dev.efang100.cc/steward/account/version
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case07_guanjia_version_update.py", line 98, in test_version_update
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='dev.efang100.cc', port=80): Max retries exceeded with url: /steward/account/version?encrypt=DES&amp;param=&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002952048&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='total_row'>
    <td>Total</td>
    <td>11</td>
    <td>0</td>
    <td>0</td>
    <td>11</td>
    <td>&nbsp;</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>

</body>
</html>
